=== KMukuch/ctuix/data/ctuix.dtd
<!ELEMENT ctuix (ctuix_panel | ctuix_selection_box | ctuix_scroll_panel)+>

<!ELEMENT ctuix_panel (ctuix_label | ctuix_button | ctuix_entry | ctuix_panel | ctuix_selection_box | ctuix_scroll_panel)*>
<!ELEMENT ctuix_selection_box (ctuix_item+)>
<!ELEMENT ctuix_scroll_panel (ctuix_label | ctuix_button | ctuix_entry | ctuix_panel | ctuix_selection_box | ctuix_scroll_panel)*>

<!ELEMENT ctuix_item (#PCDATA)>

<!ELEMENT ctuix_label (#PCDATA)>
<!ELEMENT ctuix_button (#PCDATA)>
<!ELEMENT ctuix_entry EMPTY>

<!ATTLIST ctuix_panel layout (grid | horizontal | vertical) "vertical" x CDATA #REQUIRED y CDATA #REQUIRED w CDATA #REQUIRED h CDATA #REQUIRED user_input (true | false) "false" name CDATA #IMPLIED>
<!ATTLIST ctuix_selection_box layout (horizontal | vertical) "vertical" x CDATA #REQUIRED y CDATA #REQUIRED w CDATA #REQUIRED h CDATA #REQUIRED user_input (true | false) "false" name CDATA #IMPLIED>
<!ATTLIST ctuix_scroll_panel layout (horizontal | vertical) "vertical" x CDATA #REQUIRED y CDATA #REQUIRED w CDATA #REQUIRED h CDATA #REQUIRED user_input (true | false) "false" name CDATA #IMPLIED>

<!ATTLIST ctuix_label x CDATA #REQUIRED y CDATA #REQUIRED name CDATA #IMPLIED>
<!ATTLIST ctuix_button x CDATA #REQUIRED y CDATA #REQUIRED w CDATA #REQUIRED h CDATA #REQUIRED user_input (true | false) "false" name CDATA #IMPLIED>
<!ATTLIST ctuix_entry x CDATA #REQUIRED y CDATA #REQUIRED w CDATA #REQUIRED h CDATA #REQUIRED user_input (true | false) "false" name CDATA #IMPLIED>

=== KMukuch/ctuix/data/ctuix_example_main.xml
<?xml version="1.0"?>
<!DOCTYPE ctuix_panel SYSTEM "ctuix.dtd">

<ctuix>
    <ctuix_panel x="2" y="2" w="30" h="10" name="PANEL">
        <ctuix_label x="2" y="2">LABEL</ctuix_label>
        <ctuix_panel x="2" y="4" w="10" h="5" name="PANEL">
        
        </ctuix_panel>
    </ctuix_panel>
    <ctuix_panel x="34" y="2" w="30" h="10">
        <ctuix_button x="2" y="2" w="20" h="3" name="BUTTON" id="btn">CLICK</ctuix_button>
    </ctuix_panel>
    <ctuix_selection_box x="2" y="14" w="30" h="10">
        <ctuix_item>RED</ctuix_item>
        <ctuix_item>GREEN</ctuix_item>
        <ctuix_item>BLUE</ctuix_item>
    </ctuix_selection_box>
</ctuix>
